# coding: utf-8

"""
    Zapier Embed API

    The Zapier Embed API.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@zapier.com
    Created by: https://help.zapier.com/hc/en-us
"""

from zapier_embed_python_sdk.paths.actions_action_inputs_input_choices.post import GetChoicesRaw
from zapier_embed_python_sdk.paths.actions_action_inputs.post import GetInputFieldsRaw
from zapier_embed_python_sdk.paths.actions_action_outputs.post import GetOutputFieldsRaw
from zapier_embed_python_sdk.paths.actions.get import ListAvailableActionsRaw
from zapier_embed_python_sdk.paths.actions_action_test.post import TestActionExecutionRaw


class ActionsApiRaw(
    GetChoicesRaw,
    GetInputFieldsRaw,
    GetOutputFieldsRaw,
    ListAvailableActionsRaw,
    TestActionExecutionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
