# coding: utf-8

"""
    Zapier Embed API

    The Zapier Embed API.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@zapier.com
    Created by: https://help.zapier.com/hc/en-us
"""

from zapier_embed_python_sdk.paths.authentications.post import CreateNewAuthentication
from zapier_embed_python_sdk.paths.authentications.get import GetAvailable
from zapier_embed_python_sdk.apis.tags.authentications_api_raw import AuthenticationsApiRaw


class AuthenticationsApi(
    CreateNewAuthentication,
    GetAvailable,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AuthenticationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AuthenticationsApiRaw(api_client)
