# coding: utf-8

"""
    Zapier Embed API

    The Zapier Embed API.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@zapier.com
    Created by: https://help.zapier.com/hc/en-us
"""

from zapier_embed_python_sdk.paths.authentications.post import CreateNewAuthenticationRaw
from zapier_embed_python_sdk.paths.authentications.get import GetAvailableRaw


class AuthenticationsApiRaw(
    CreateNewAuthenticationRaw,
    GetAvailableRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
