# coding: utf-8

"""
    Zapier Embed API

    The Zapier Embed API.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@zapier.com
    Created by: https://help.zapier.com/hc/en-us
"""

from zapier_embed_python_sdk.paths.zap_runs.get import GetZapRuns
from zapier_embed_python_sdk.apis.tags.experimental_api_raw import ExperimentalApiRaw


class ExperimentalApi(
    GetZapRuns,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ExperimentalApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ExperimentalApiRaw(api_client)
