# coding: utf-8

"""
    Zapier Embed API

    The Zapier Embed API.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@zapier.com
    Created by: https://help.zapier.com/hc/en-us
"""

from zapier_embed_python_sdk.paths.zaps.post import CreateZapRaw
from zapier_embed_python_sdk.paths.zaps.get import GetFilteredZapsRaw


class ZapsApiRaw(
    CreateZapRaw,
    GetFilteredZapsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
