# coding: utf-8

"""
    Zapier Embed API

    The Zapier Embed API.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@zapier.com
    Created by: https://help.zapier.com/hc/en-us
"""

from zapier_embed_python_sdk.paths.zaps.post import CreateZap
from zapier_embed_python_sdk.paths.zaps.get import GetFilteredZaps
from zapier_embed_python_sdk.apis.tags.zaps_api_raw import ZapsApiRaw


class ZapsApi(
    CreateZap,
    GetFilteredZaps,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ZapsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ZapsApiRaw(api_client)
